name: CI jobs
on:
  push:
    branches:
      - master
      - r[0-9]+.*
  pull_request:
    branches:
      - master
      - r[0-9]+.*
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        run: |
          java -version
          mvn -version
          mvn clean install -B -U -e -Dlint.skip=true
      - name: Run lint checks
        run: |
          mvn compiler:compile -Pdev,jdk11 -B -U -e
      - name: Deploy snapshot artifacts
        if: github.event_name == 'push' && contains(github.ref, 'master')
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.CI_DEPLOY_USERNAME }}</username><password>${{ secrets.CI_DEPLOY_PASSWORD }}</password></server></servers></settings>" > settings.xml
          mvn deploy -B -U -e
